services:
  db:
    image: ankane/pgvector:v0.5.1
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=doc_db
